### PR TITLE
README: Mention ocaml-ci-scripts for setup

### PR DESCRIPTION
**Pull request by mc10**
This should make the process of setting up Travis be a bit more approachable for new projects.

### CODE REVIEW

**Comment by pmetzger** [comment]
Some of these instructions don't apply because the individual repository committers can't turn on Travis etc.

I'd rather we have our own short document explaining how to set up Travis on an ocaml-community project, perhaps based on this text. Would you be willing to write such a document?

**Comment by mc10** [comment]
I'm not entirely sure when the situation you've mentioned would apply; doesn't the owner of the repo need to approve moving the repo into this organization anyways? In that case, they should be able to turn on Travis themselves.

**Comment by pmetzger** [comment]
> I'm not entirely sure when the situation you've mentioned would apply; doesn't the owner of the repo need to approve moving the repo into this organization anyways? In that case, they should be able to turn on Travis themselves.

The owner of the organization turns on Travis. The person creating the `.travis.yml` file will be the maintainer of the project, not necessarily one of the two or three organization owners.

**Comment by pmetzger** [comment]
@Drup I didn't know about autoci. It looks cool. Do you want to maybe create an issue so we don't forget about it?

**Pull request closed without merging**
